on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  python:
    runs-on: codeberg-tiny-lazy
    env:
      # Skip blueprint, msgfmt, and GLib schemas on CI
      SKIP_BLUEPRINT: "1"
      SKIP_MSGFMT: "1"
      SKIP_SCHEMAS: "1"
      # Don't sync for every uv call, we just sync once at the beginning
      UV_NO_SYNC: "1"
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      # Don't install pygobject, because we're lacking all their system dependencies.
      - run: uv sync --only-dev --locked --no-install-package pygobject --no-install-project
      - run: uv run poe lint:types
      - run: uv run poe lint:python
      - run: uv run poe format:python --check
