
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.swsnr]
url = "https://codeberg.org/swsnr/rust-supply-chain/raw/branch/main/audits.toml"

[policy.turnon]
criteria = "safe-to-run"

[[exemptions.bitflags]]
version = "2.11.0"
criteria = "safe-to-run"

[[exemptions.cairo-rs]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.cairo-sys-rs]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.cfg-expr]]
version = "0.20.6"
criteria = "safe-to-run"

[[exemptions.concurrent-queue]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.event-listener]]
version = "5.3.1"
criteria = "safe-to-run"

[[exemptions.event-listener-strategy]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.futures]]
version = "0.3.32"
criteria = "safe-to-run"

[[exemptions.futures-channel]]
version = "0.3.32"
criteria = "safe-to-run"

[[exemptions.futures-core]]
version = "0.3.32"
criteria = "safe-to-run"

[[exemptions.futures-executor]]
version = "0.3.32"
criteria = "safe-to-run"

[[exemptions.futures-io]]
version = "0.3.32"
criteria = "safe-to-run"

[[exemptions.futures-macro]]
version = "0.3.32"
criteria = "safe-to-run"

[[exemptions.futures-sink]]
version = "0.3.32"
criteria = "safe-to-run"

[[exemptions.futures-task]]
version = "0.3.32"
criteria = "safe-to-run"

[[exemptions.futures-util]]
version = "0.3.32"
criteria = "safe-to-run"

[[exemptions.gdk-pixbuf]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.gdk-pixbuf-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.gdk4]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.gdk4-sys]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.gio-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.gio-unix]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.gio-unix-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.glib-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.gobject-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.graphene-rs]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.graphene-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.gsk4]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.gsk4-sys]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.gtk4-macros]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.gtk4-sys]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.16.1"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.13.0"
criteria = "safe-to-run"

[[exemptions.linux-raw-sys]]
version = "0.12.1"
criteria = "safe-to-run"

[[exemptions.pango]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.pango-sys]]
version = "0.22.0"
criteria = "safe-to-run"

[[exemptions.pin-project-lite]]
version = "0.2.17"
criteria = "safe-to-run"

[[exemptions.proc-macro-crate]]
version = "3.5.0"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.106"
criteria = "safe-to-run"

[[exemptions.quote]]
version = "1.0.45"
criteria = "safe-to-run"

[[exemptions.rustix]]
version = "1.1.4"
criteria = "safe-to-run"

[[exemptions.slab]]
version = "0.4.12"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "2.0.117"
criteria = "safe-to-run"

[[exemptions.toml_datetime]]
version = "1.0.0+spec-1.1.0"
criteria = "safe-to-run"

[[exemptions.toml_edit]]
version = "0.25.3+spec-1.1.0"
criteria = "safe-to-run"

[[exemptions.toml_parser]]
version = "1.0.9+spec-1.1.0"
criteria = "safe-to-run"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-run"

[[exemptions.winnow]]
version = "0.7.14"
criteria = "safe-to-run"

[[exemptions.zmij]]
version = "1.0.21"
criteria = "safe-to-run"
